// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamCopy.Data;

#nullable disable

namespace SteamCopy.Migrations
{
    [DbContext(typeof(SteamCopyContext))]
    [Migration("20230509103652_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SteamCopy.Models.SteamGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SteamGames");
                });

            modelBuilder.Entity("SteamCopy.Models.SteamGameDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallQuality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(2,1)");

                    b.Property<int>("SteamGameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SteamGameId")
                        .IsUnique();

                    b.ToTable("SteamGameDetails");
                });

            modelBuilder.Entity("SteamCopy.Models.SteamGameDetail", b =>
                {
                    b.HasOne("SteamCopy.Models.SteamGame", null)
                        .WithOne("SteamGameDetail")
                        .HasForeignKey("SteamCopy.Models.SteamGameDetail", "SteamGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SteamCopy.Models.SteamGame", b =>
                {
                    b.Navigation("SteamGameDetail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
